### ISSUE TITLE
Bad link in your readme

### ISSUE THREAD

**Issue by steinbring** [jastreich/forms#1]
The link (to the documentation) you provide in your readme.MD file requires a login.

**Comment by steinbring** [comment]
Can I suggest just adding your documentation to the readme? That way, it would be versioned.

**Comment by jastreich** [comment]
How the documentation is distributed is currently being thought.  The documentation is generated by our internal build process, and includes a full class list, with definitions of each function for each class, and any defined static constant values.  You can see the current documentation is in the doc folder of this project.

I need to update the Readme at the very least, and at the most need to rethink where conical documentation will live.
